# -*- coding: utf-8 -*-
"""a_vendas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/CleidisonWCley/33929c0a6c63eecf56279f4fefe6d9aa/a_vendas.ipynb
"""



"""# **Análise de Vendas com Pandas**

## **Dataset:**


*   Cliente

*   Produto

*   Categoria

*   Valor

*   Data


## **Métodos:**


*   Leitura com pandas.read_csv
*   Conversão de datas com pd.to_datetime

*   Agrupamento de dados com groupby
*   Visualização com matplotlib.pyplot

## **Prints:**

*   df.head() → mostra as primeiras linhas
*   df.info() → mostra tipo de dados e colunas
"""

!pip install faker

from faker import Faker
import random
import pandas as pd

fake = Faker ("Pt_BR")

categorias = ["Eletronicos", "Roupas" , "Alimentos" , "Livros","Beleza", "JOGOS" ]
produtos = {
    "Eletronicos" :  ["Smartphone" ,"Notebook", "Fone de ouvido", "TV", "PCGAMER"],
    "Roupas" : ["Camisa", "Calça", "Jaqueta", "Vestido", "Saia"],
    "Alimentos" : ["Arroz", "Feijão", "Macarrão", "Leite", "Ovos"],
    "Livros" : ["Romance", "Ficção científica", "Terror", "Aventura", "Suspense"],
    "Beleza" : ["Perfume", "Creme", "Sabonete", "Shampoo", "Bómbóm"],
    "JOGOS" : ["Guardian Tales", "Genshin Impact", "Roblox", "GTA V" , "Minecraft"]
}

dados = []
for _ in range(1000): #Numero de linhas
  categoria = random.choice(categorias)
  produto = random.choice(produtos[categoria])
  cliente = fake.first_name()
  valor = round(random.uniform(10, 2000), 2)
  data = fake.date_between (start_date= "-1y", end_date="today")
  dados.append([cliente, produto, categoria, valor, data])

dp = pd.DataFrame(dados, columns=["Cliente", "Produto", "Categoria", "Valor", "Data"])
dp.to_csv("dados_fakes.csv", index=False, encoding="utf-8")

print("Arquivo vendas.csv gerado com sucesso!")
print(dp.head())

"""### **Resultados:**"""

# Bibliotecas
import pandas as pd
import matplotlib.pyplot as plt

# Configurações de exibição
pd.set_option('display.float_format', 'R${:,.2f}'.format)

# Lê o arquivo CSV
df = pd.read_csv("dados_fakes.csv")

# Converte coluna de data para datetime
df["Data"] = pd.to_datetime(df["Data"])
df["Mes"] = df["Data"].dt.to_period("M")

# Mostra primeiras linhas
print("🔍 Primeiras linhas do dataset:")
print(df.head())

# Informações gerais
print("\nℹ️ Informações do DataFrame:")
print(df.info())

# 1. Qual cliente gastou mais no período?
cliente_top = df.groupby("Cliente")["Valor"].sum().sort_values(ascending=False)
print("\n1️⃣ Cliente que mais gastou no período:")
print(cliente_top.head(1))

cliente_top.head(10).plot(kind="bar", title="Top 10 Clientes por Gastos", ylabel="Valor (R$)", figsize=(10, 5))
plt.tight_layout()
plt.show()

# 2. Categoria que mais fatura
categoria_faturamento = df.groupby("Categoria")["Valor"].sum().sort_values(ascending=False)
print("\n2️⃣ Categoria com maior faturamento:")
print(categoria_faturamento)

categoria_faturamento.plot(kind="bar", title="Faturamento por Categoria", ylabel="Valor (R$)", color="skyblue")
plt.tight_layout()
plt.show()

# 3. Produto mais vendido (por número de vendas)
produto_mais_vendido = df["Produto"].value_counts().head(1)
print("\n3️⃣ Produto mais vendido (em número de vendas):")
print(produto_mais_vendido)

df["Produto"].value_counts().head(10).plot(kind="bar", title="Top 10 Produtos Mais Vendidos", color="orange")
plt.tight_layout()
plt.show()

# 4. Existe sazonalidade nas vendas?
vendas_por_mes = df.groupby("Mes")["Valor"].sum()
print("\n4️⃣ Faturamento por mês:")
print(vendas_por_mes)

vendas_por_mes.plot(kind="line", title="Faturamento Mensal", marker="o", figsize=(10, 5))
plt.ylabel("Valor (R$)")
plt.grid(True)
plt.tight_layout()
plt.show()

# 5. Cliente que mais comprou em valor total (igual ao cliente que mais gastou)
print("\n5️⃣ Cliente com maior valor total de compras:")
print(cliente_top.head(1))

# 6. Quantas vendas por mês (gráfico de barras)
vendas_por_mes_qtd = df["Mes"].value_counts().sort_index()
print("\n6️⃣ Quantidade de vendas por mês:")
print(vendas_por_mes_qtd)

vendas_por_mes_qtd.plot(kind="bar", title="Quantidade de Vendas por Mês", color="green", figsize=(10, 5))
plt.ylabel("Número de Vendas")
plt.tight_layout()
plt.show()

# 7. Gráfico adicional (livre escolha): Faturamento por produto
faturamento_produto = df.groupby("Produto")["Valor"].sum().sort_values(ascending=False).head(10)
faturamento_produto.plot(kind="barh", title="Top 10 Produtos por Faturamento", color="purple")
plt.xlabel("Valor (R$)")
plt.tight_layout()
plt.show()

"""## **Limitações:**

- Os dados são simulados, portanto não representam uma empresa real.

- Não há coluna de quantidade vendida, dificultando análises de volume.

- Não é possível calcular lucro, pois não há custo de produto.

- Produtos e categorias foram definidos de forma aleatória, sem padrão de mercado.
"""

# Exibe informações estruturais do DataFrame
print("ℹ️ Informações do DataFrame:")
print(df.info())

print("📊 Estatísticas descritivas (df.describe()):")
print(df.describe())

faturamento_categoria = df.groupby("Categoria")["Valor"].sum().sort_values(ascending=False)

print("💰 Faturamento total por categoria:")
print(faturamento_categoria)

vendas_por_mes = df.groupby("Mes").size()

print("📅 Quantidade total de vendas por mês:")
print(vendas_por_mes)

import matplotlib.pyplot as plt

# Filtrar apenas vendas da categoria "JOGOS"
df_jogos = df[df["Categoria"] == "JOGOS"]

# Contar quantas vezes cada jogo foi vendido
jogos_mais_vendidos = df_jogos["Produto"].value_counts()

# Plotar o gráfico de barras
plt.figure(figsize=(8, 5))
jogos_mais_vendidos.plot(kind='bar', color='royalblue')
plt.title("🎮 Jogos mais vendidos (Categoria: JOGOS)", fontsize=14)
plt.xlabel("Jogo")
plt.ylabel("Quantidade de Vendas")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Filtrar vendas da categoria "Eletronicos"
df_eletronicos = df[df["Categoria"] == "Eletronicos"]

# Agrupar por produto e somar o valor total das vendas
faturamento_eletronicos = df_eletronicos.groupby("Produto")["Valor"].sum().sort_values(ascending=False)

# Plotar gráfico de barras
plt.figure(figsize=(8,5))
faturamento_eletronicos.plot(kind='bar', color='darkorange')
plt.title("💻 Faturamento por Produto - Categoria Eletronicos", fontsize=14)
plt.xlabel("Produto")
plt.ylabel("Faturamento Total (R$)")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Filtrar vendas da categoria "Roupas"
df_roupas = df[df["Categoria"] == "Roupas"]

# Agrupar por produto e somar o valor total das vendas
faturamento_roupas = df_roupas.groupby("Produto")["Valor"].sum().sort_values(ascending=False)

# Plotar gráfico de barras
plt.figure(figsize=(8,5))
faturamento_roupas.plot(kind='bar', color='mediumseagreen')
plt.title("👗 Faturamento por Produto - Categoria Roupas", fontsize=14)
plt.xlabel("Produto")
plt.ylabel("Faturamento Total (R$)")
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()